function formatfigure(figHandle, figWidth, figHeight)

set(figHandle, ...
    'color', 'white', 'Units', 'inches', ...
    'PaperSize', [figWidth, figHeight], ...
    'PaperPosition', [0, 0, figWidth, figHeight], ...
    'PaperPositionMode', 'manual');

hAllAxes = findobj(figHandle,'type','axes');
hLeg = findobj(hAllAxes,'tag','legend');
hAxes = setdiff(hAllAxes, hLeg);

set(hAxes, 'box', 'off', 'tickdir', 'out', 'linewidth', 1.5, ...
    'fontsize', 16, 'Units', 'inches', ...
    'ActivePositionProperty', 'outerposition');


end