function [CellPropertiesCell, NucleusPropertiesCell] = ...
    analyzecells(contactWidth, nucleusWidth)
% Select files.
[cadherinFileNameStr, folderNameStr] = uigetfile('*.tif', ...
    'Select cadherin TIF', '/home/jiongyi/Documents/MATLAB/martijn');
nucleusFileNameStr = uigetfile('*.tif', ...
    'Select nucleus TIF', folderNameStr);

% Load files.
cadherinStack = imstack([folderNameStr, cadherinFileNameStr]);
nucleusStack = imstack([folderNameStr, nucleusFileNameStr]);

% Mask cells.
noFrames = size(cadherinStack, 3);
[ContactCell, NucleusCell] = arrayfun(@(x) ...
    maskcells(cadherinStack(:, :, x), nucleusStack(:, :, x), ...
    contactWidth, nucleusWidth), 1 : noFrames, 'UniformOutput', false);
[CellPropertiesCell, NucleusPropertiesCell] = cellfun(@(x, y) ...
    cellproperties(x, y), ContactCell, NucleusCell, ...
    'UniformOutput', false);