function [CellProperties, NucleusProperties] = cellproperties(Cell, ...
    Nucleus)
CellProperties = regionprops(Cell.bwIm, Cell.rawIm, ...
    'Area', 'BoundingBox', 'Centroid', 'Eccentricity', ...
    'MajorAxisLength', 'MinorAxisLength', 'Orientation', ...
    'PixelIdxList', 'MeanIntensity');
NucleusProperties = regionprops(Nucleus.bwIm, Nucleus.rawIm, ...
    'Area', 'BoundingBox', 'Centroid', 'Eccentricity', ...
    'MajorAxisLength', 'MinorAxisLength', 'Orientation', ...
    'PixelIdxList', 'MeanIntensity');
end